### ISSUE TITLE
Panic on empty path segments in request

### ISSUE THREAD

**Issue by cskr** [go-chi/chi#277]
`chi.URLParam` panics when path segments matching path variables is empty.

chi version: 94e6bc0
Go version: go1.9.2 linux/amd64

Sample code for reproduction:

```
package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	mux := chi.NewMux()
	mux.Get("/prefix/{x}/{y}/suffix", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, chi.URLParam(r, "x"), chi.URLParam(r, "y"))
	})

	http.ListenAndServe(":8080", mux)
}
```

curl command:

```
curl 'http://localhost:8080/prefix///suffix'
```

Panic:

```
2017/11/11 19:31:39 http: panic serving 127.0.0.1:52118: runtime error: index out of range
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc42007ad20)
	$GOROOT/src/net/http/server.go:1697 +0xd0
panic(0x675140, 0x82f160)
	$GOROOT/src/runtime/panic.go:491 +0x283
github.com/go-chi/chi.(*Context).URLParam(0xc4200fc000, 0x6c5b1c, 0x1, 0x0, 0xc420010ac0)
	$HOME/go/src/github.com/go-chi/chi/context.go:74 +0x102
github.com/go-chi/chi.URLParam(0xc4200f6100, 0x6c5b1c, 0x1, 0x8, 0xc4200ee048)
	$HOME/go/src/github.com/go-chi/chi/context.go:108 +0x6e
main.main.func1(0x805f20, 0xc4200f8000, 0xc4200f6100)
	$HOME/test.go:13 +0x55
net/http.HandlerFunc.ServeHTTP(0x6d8940, 0x805f20, 0xc4200f8000, 0xc4200f6100)
	$GOROOT/src/net/http/server.go:1918 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc420060120, 0x805f20, 0xc4200f8000, 0xc4200f6100)
	$HOME/go/src/github.com/go-chi/chi/mux.go:428 +0x289
github.com/go-chi/chi.(*Mux).(github.com/go-chi/chi.routeHTTP)-fm(0x805f20, 0xc4200f8000, 0xc4200f6100)
	$HOME/go/src/github.com/go-chi/chi/mux.go:372 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420010a20, 0x805f20, 0xc4200f8000, 0xc4200f6100)
	$GOROOT/src/net/http/server.go:1918 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc420060120, 0x805f20, 0xc4200f8000, 0xc4200f6000)
	$HOME/go/src/github.com/go-chi/chi/mux.go:81 +0x221
net/http.serverHandler.ServeHTTP(0xc420078dd0, 0x805f20, 0xc4200f8000, 0xc4200f6000)
	$GOROOT/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42007ad20, 0x806460, 0xc42005e280)
	$GOROOT/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	$GOROOT/src/net/http/server.go:2720 +0x288
```

**Comment by diegobernardes** [comment]
Got this problem too. The panic is being generated by [this](https://github.com/go-chi/chi/blob/c82a10ad80a5eab1d6b77ff5e96bdb774757d5a6/context.go#L71..L78):

https://github.com/go-chi/chi/blob/c82a10ad80a5eab1d6b77ff5e96bdb774757d5a6/context.go#L74

It should check the slice size before read or the slice should always be initialized with default values.

**Comment by cskr** [comment]
URL should be sanitized, like [`ServeMux`](https://golang.org/pkg/net/http/#ServeMux) does, before routing.

**Comment by pkieltyka** [comment]
Thanks for the report gents. The fix was actually very simple, have a look at the commit.

However, its possible to also build a path cleaning middleware similar to stdlib ServeMux as @cskr pointed out.
