### ISSUE TITLE
RedirectSlashes & StripSlashes don't work?

### ISSUE THREAD

**Issue by Tom29** [go-chi/chi#324]
Here is my code, no matter i've tried, can't get it work.
```
router := chi.NewRouter()

	router.Route("/", func(router chi.Router) {
		router.Use(middleware.RedirectSlashes)
		router.Get("/", func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte("welcome"))
		})
		router.Get("/foo", func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte("welcome"))
		})
	})

	http.ListenAndServe(":3000", router)
```

And result:
```

2018/06/23 13:46:24 http: panic serving [::1]:53027: interface conversion: interface {} is nil, not *chi.Context
goroutine 60 [running]:
net/http.(*conn).serve.func1(0xc4202188c0)
        /usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x137e0c0, 0xc42013d780)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/go-chi/chi.RouteContext(0x15b5960, 0xc42013b590, 0x5)
        /Hdd/go/src/github.com/go-chi/chi/context.go:102 +0x88
github.com/go-chi/chi/middleware.RedirectSlashes.func1(0x15b4de0, 0xc42013d740, 0xc420145b00)
        /Hdd/go/src/github.com/go-chi/chi/middleware/strip.go:34 +0x5d
net/http.HandlerFunc.ServeHTTP(0xc4200de720, 0x15b4de0, 0xc42013d740, 0xc420145b00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
test/vendor/github.com/go-chi/chi.(*Mux).ServeHTTP(0xc420060300, 0x15b4de0, 0xc42013d740, 0xc420145b00)
        /Hdd/go/src/test/vendor/github.com/go-chi/chi/mux.go:69 +0x32d
test/vendor/github.com/go-chi/chi.(*Mux).Mount.func1(0x15b4de0, 0xc42013d740, 0xc420145b00)
        /Hdd/go/src/test/vendor/github.com/go-chi/chi/mux.go:291 +0x107
net/http.HandlerFunc.ServeHTTP(0xc4200de780, 0x15b4de0, 0xc42013d740, 0xc420145b00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
test/vendor/github.com/go-chi/chi.(*Mux).routeHTTP(0xc420060240, 0x15b4de0, 0xc42013d740, 0xc420145b00)
        /Hdd/go/src/test/vendor/github.com/go-chi/chi/mux.go:424 +0x289
test/vendor/github.com/go-chi/chi.(*Mux).(test/vendor/github.com/go-chi/chi.routeHTTP)-fm(0x15b4de0, 0xc42013d740, 0xc420145b00)
        /Hdd/go/src/test/vendor/github.com/go-chi/chi/mux.go:368 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420010d40, 0x15b4de0, 0xc42013d740, 0xc420145b00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
github.com/go-chi/chi/middleware.Compress.func1.1(0x15b50a0, 0xc420156c40, 0xc420145b00)
        /Hdd/go/src/github.com/go-chi/chi/middleware/compress.go:66 +0x15b
net/http.HandlerFunc.ServeHTTP(0xc4200797a0, 0x15b50a0, 0xc420156c40, 0xc420145b00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
test/vendor/github.com/go-chi/chi.(*Mux).ServeHTTP(0xc420060240, 0x15b50a0, 0xc420156c40, 0xc420145a00)
        /Hdd/go/src/test/vendor/github.com/go-chi/chi/mux.go:81 +0x221
net/http.serverHandler.ServeHTTP(0xc42007d380, 0x15b50a0, 0xc420156c40, 0xc420145a00)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4202188c0, 0x15b58a0, 0xc42013d640)
        /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by Tom29** [comment]
It was the fault from govendor, i use govendor to fetch package but somehow itsn't the latest version ?!
