### ISSUE TITLE
Test segfaulting on x86_64: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by eclipseo** [go-chi/chi#572]
Hi,

I'm running the tests with Go 1.15.6 on Fedora Rawhide and it is failing with:

```
Testing    in: /builddir/build/BUILD/chi-1.5.1/_build/src
         PATH: /builddir/build/BUILD/chi-1.5.1/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/chi-1.5.1/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags " -X github.com/go-chi/chi/version=1.5.1 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  '"
      testing: github.com/go-chi/chi
github.com/go-chi/chi
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x55c8bc5eb90f]
goroutine 231663 [running]:
context.(*cancelCtx).Done(0x0, 0xc0000160e0)
	/usr/lib/golang/src/context/context.go:361 +0x2f
github.com/go-chi/chi.(*directContext).Done(0xc0002345b0, 0xc000565e30)
	/builddir/build/BUILD/chi-1.5.1/_build/src/github.com/go-chi/chi/context.go:161 +0x3c
context.parentCancelCtx(0x55c8bca4cd20, 0xc0002345b0, 0x0, 0x0)
	/usr/lib/golang/src/context/context.go:298 +0x37
context.removeChild(0x55c8bca4cd20, 0xc0002345b0, 0x55c8bca48aa0, 0xc000880ea0)
	/usr/lib/golang/src/context/context.go:317 +0x3b
context.(*timerCtx).cancel(0xc000880ea0, 0xc000aab701, 0x55c8bca474c0, 0x55c8bcc3d680)
	/usr/lib/golang/src/context/context.go:482 +0x145
context.WithDeadline.func2()
	/usr/lib/golang/src/context/context.go:452 +0x49
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:167 +0x46
exit status 2
FAIL	github.com/go-chi/chi	0.478s
```

Please note this is failing only on AMD64 arches, I have no issue on armv7hl, aarch64, i686 or ppc64le.

See logs at https://koji.fedoraproject.org/koji/taskinfo?taskID=59708511

**Comment by eclipseo** [comment]
Seems to fails randomly.
