### ISSUE TITLE
TestMuxContextIsThreadSafe occasional crash

### ISSUE THREAD

**Issue by rantala** [go-chi/chi#576]
`TestMuxContextIsThreadSafe` test is occasionally crashing:

```
$ go test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6bddd0]

goroutine 173608 [running]:
github.com/go-chi/chi.(*directContext).Done(0xc00036c680, 0xad696809bbda0a01)
        /home/tomranta/git/chi/context.go:161 +0x30
context.parentCancelCtx(0x812580, 0xc00036c680, 0x0, 0x0)
        /usr/lib/golang/src/context/context.go:295 +0x35
context.removeChild(0x812580, 0xc00036c680, 0x80dee0, 0xc00059e300)
        /usr/lib/golang/src/context/context.go:314 +0x39
context.(*timerCtx).cancel(0xc00059e300, 0xc0002e1f01, 0x80c700, 0xa6a0c0)
        /usr/lib/golang/src/context/context.go:476 +0x141
context.WithDeadline.func2()
        /usr/lib/golang/src/context/context.go:446 +0x47
created by time.goFunc
        /usr/lib/golang/src/time/sleep.go:168 +0x44
exit status 2
FAIL    github.com/go-chi/chi   0.159s
```

Running with the race detector produces warnings:
```
$ go test -race
==================
WARNING: DATA RACE
Write at 0x00c00069eb50 by goroutine 93:
  github.com/go-chi/chi.(*Context).Reset()
      /home/tomranta/git/chi/context.go:95 +0x3a7
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      /home/tomranta/git/chi/mux.go:78 +0x18a
  github.com/go-chi/chi.TestMuxContextIsThreadSafe.func2()
      /home/tomranta/git/chi/mux_test.go:1586 +0xdf

Previous read at 0x00c00069eb50 by goroutine 87:
  github.com/go-chi/chi.(*directContext).Value()
      /home/tomranta/git/chi/context.go:172 +0x85
  context.parentCancelCtx()
      /usr/lib/golang/src/context/context.go:299 +0xb8
  context.removeChild()
      /usr/lib/golang/src/context/context.go:314 +0x46
  context.(*timerCtx).cancel()
      /usr/lib/golang/src/context/context.go:476 +0x176
  context.WithDeadline.func2()
      /usr/lib/golang/src/context/context.go:446 +0x78

Goroutine 93 (running) created at:
  github.com/go-chi/chi.TestMuxContextIsThreadSafe()
      /home/tomranta/git/chi/mux_test.go:1571 +0x10e
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:1050 +0x1eb

Goroutine 87 (finished) created at:
  time.goFunc()
      /usr/lib/golang/src/time/sleep.go:168 +0x51
==================
==================
WARNING: DATA RACE
Read at 0x00c00069e670 by goroutine 17:
  github.com/go-chi/chi.(*directContext).Done()
      /home/tomranta/git/chi/context.go:161 +0x41
  context.parentCancelCtx()
      /usr/lib/golang/src/context/context.go:295 +0x42
  context.removeChild()
      /usr/lib/golang/src/context/context.go:314 +0x46
  context.(*timerCtx).cancel()
      /usr/lib/golang/src/context/context.go:476 +0x176
  context.WithDeadline.func2()
      /usr/lib/golang/src/context/context.go:446 +0x78

Previous write at 0x00c00069e670 by goroutine 91:
  github.com/go-chi/chi.(*Context).Reset()
      /home/tomranta/git/chi/context.go:95 +0x3a7
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      /home/tomranta/git/chi/mux.go:78 +0x18a
  github.com/go-chi/chi.TestMuxContextIsThreadSafe.func2()
      /home/tomranta/git/chi/mux_test.go:1586 +0xdf

Goroutine 17 (running) created at:
  time.goFunc()
      /usr/lib/golang/src/time/sleep.go:168 +0x51

Goroutine 91 (running) created at:
  github.com/go-chi/chi.TestMuxContextIsThreadSafe()
      /home/tomranta/git/chi/mux_test.go:1571 +0x10e
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:1050 +0x1eb
==================
...
```

Testing with go 1.14:
```
$ go version
go version go1.14.13 linux/amd64
```

**Comment by rantala** [comment]
Patching the testcase fixes the issue for me, but I'm not sure if this is actually exposing some real bug.

If I understand the testcase right, the context is getting canceled later anyway, so we would not need to do the canceling here:

```
$ git diff
diff --git a/mux_test.go b/mux_test.go
index 36b2716..2ed586f 100644
--- a/mux_test.go
+++ b/mux_test.go
@@ -1558,10 +1558,7 @@ func TestMuxSubrouterWildcardParam(t *testing.T) {
 func TestMuxContextIsThreadSafe(t *testing.T) {
        router := NewRouter()
        router.Get("/{id}", func(w http.ResponseWriter, r *http.Request) {
-               ctx, cancel := context.WithTimeout(r.Context(), 1*time.Millisecond)
-               defer cancel()
-
-               <-ctx.Done()
+               <-r.Context().Done()
        })
 
        wg := sync.WaitGroup{}
```

**Comment by pkieltyka** [comment]
@rantala thanks for bringing this to my attention. Indeed there looks to be an issue with an allocation optimization merged in a few weeks ago; https://github.com/go-chi/chi/blob/master/mux.go#L83

if you replace that line with, `r = r.WithContext(context.WithValue(r.Context(), RouteCtxKey, rctx))` (as was prior implementation), then all tests pass with -race flag. I'll be looking into if we can fix this race condition with the implementation in master as it contains a very small optimization, otherwise I will go back to the original.

**Comment by pkieltyka** [comment]
FYI: https://github.com/go-chi/chi/pull/581
