### ISSUE TITLE
Mux methods `Routes` and `Mount` are not safe for concurrent use

### ISSUE THREAD

**Issue by matej-g** [go-chi/chi#716]
Hello :wave:,

I'm reporting from the [Observatorium project](https://github.com/observatorium), where we've been using Chi to much satisfaction! Thanks for all your hard work. We are currently running chi version `4.1.2`, but it looks like this problem could exists also in later and current version.

In our service, we are leveraging the `Routes()` method on mux to list existing API routes on our root path. One of our recent test runs has failed due to detected concurrent read / write induced panic, I'm pasting the full output below.

<details>

```
06:18:47 observatorium_api: fatal error: concurrent map read and map write
06:18:47 observatorium_api: goroutine 1 [running]:
06:18:47 observatorium_api: runtime.throw(0x1cc0714,
06:18:47 observatorium_api: 0x21)
06:18:47 observatorium_api: /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0005deda0 sp=0xc0005ded70 pc=0x438652
06:18:47 observatorium_api: runtime.mapaccess1_fast64(0x1a8bd40, 0xc0005127e0, 0x1, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/runtime/map_fast64.go:21 +0x198 fp=0xc0005dedc8 sp=0xc0005deda0 pc=0x412998
06:18:47 observatorium_api: github.com/go-chi/chi.(*node).routes.func1(0xc0005127e0, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/tree.go:597 +0x65 fp=0xc0005df058 sp=0xc0005dedc8 pc=0x7a4685
06:18:47 observatorium_api: github.com/go-chi/chi.(*node).walk(0xc0004b1ae0, 0xc0005df350, 0xc0000fee00)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/tree.go:645 +0x144 fp=0xc0005df110 sp=0xc0005df058 pc=0x7a3764
06:18:47 observatorium_api: github.com/go-chi/chi.(*node).walk(0xc0004b1a40, 0xc0005df350, 0x200)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/tree.go:652 +0xbd fp=0xc0005df1c8 sp=0xc0005df110 pc=0x7a36dd
06:18:47 observatorium_api: github.com/go-chi/chi.(*node).walk(0xc0004b19a0, 0xc0005df350, 0x40ddd2)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/tree.go:652 +0xbd fp=0xc0005df280 sp=0xc0005df1c8 pc=0x7a36dd
06:18:47 observatorium_api: github.com/go-chi/chi.(*node).walk(0xc0004b0aa0, 0xc0005df350, 0x2)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/tree.go:652 +0xbd fp=0xc0005df338 sp=0xc0005df280 pc=0x7a36dd
06:18:47 observatorium_api: github.com/go-chi/chi.(*node).routes(0xc0004b0aa0, 0xc000360630, 0x1, 0x1)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/tree.go:596 +0x65 fp=0xc0005df388 sp=0xc0005df338 pc=0x7a35e5
06:18:47 observatorium_api: github.com/go-chi/chi.(*Mux).Routes(...)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:322
06:18:47 observatorium_api: main.main()
06:18:47 observatorium_api: /home/circleci/project/main.go:643 +0x30aa fp=0xc0005dff88 sp=0xc0005df388 pc=0x18cbdea
06:18:47 observatorium_api: runtime.main()
06:18:47 observatorium_api: /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc0005dffe0 sp=0xc0005dff88 pc=0x43ae96
06:18:47 observatorium_api: runtime.goexit()
06:18:47 observatorium_api: /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005dffe8 sp=0xc0005dffe0 pc=0x472381
06:18:47 observatorium_api: goroutine 18 [chan receive]:
06:18:47 observatorium_api: k8s.io/klog/v2.(*loggingT).flushDaemon(0x2b3ff80)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1169 +0x8b
06:18:47 observatorium_api: created by k8s.io/klog/v2.init.0
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:420 +0xdf
06:18:47 observatorium_api: goroutine 54 [chan receive]:
06:18:47 observatorium_api: main.main.func4.1(0xc00035d130, 0xc00000fc40, 0x1edf920, 0xc0000c0690, 0xc000415068, 0xc000388630, 0x1f3d3d8, 0xc000181f20, 0xc00050dd10, 0xc000443af0, ...)
06:18:47 observatorium_api: /home/circleci/project/main.go:501 +0xd5
06:18:47 observatorium_api: created by main.main.func4
06:18:47 observatorium_api: /home/circleci/project/main.go:500 +0x7d1
06:18:47 observatorium_api: goroutine 55 [select]:
06:18:47 observatorium_api: net/http.(*http2ClientConn).roundTrip(0xc000508180, 0xc0003b8400, 0x0, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:7668 +0x9c5
06:18:47 observatorium_api: net/http.(*http2Transport).RoundTripOpt(0xc000245810, 0xc0003b8400, 0xc000420f00, 0xc000384b00, 0xc000420f30, 0x1d6a3d8)
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:6981 +0x1a5
06:18:47 observatorium_api: net/http.(*http2Transport).RoundTrip(0xc000245810, 0xc0003b8400, 0x0, 0xc00003f590, 0x5)
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:6942 +0x3a
06:18:47 observatorium_api: net/http.(*Transport).roundTrip(0xc000420f00, 0xc0003b8400, 0x1c516e0, 0x1bc7301, 0xc0003b8400)
06:18:47 observatorium_api: /usr/local/go/src/net/http/transport.go:590 +0x865
06:18:47 observatorium_api: net/http.(*Transport).RoundTrip(0xc000420f00, 0xc0003b8400, 0xc000420f00, 0xc08624130b001e15, 0x12f8827ac)
06:18:47 observatorium_api: /usr/local/go/src/net/http/roundtrip.go:17 +0x35
06:18:47 observatorium_api: net/http.send(0xc0003b8300, 0x1ee2a80, 0xc000420f00, 0xc08624130b001e15, 0x12f8827ac, 0x2b3fbe0, 0xc00000fcd8, 0xc08624130b001e15, 0x1, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/net/http/client.go:251 +0x454
06:18:47 observatorium_api: net/http.(*Client).send(0xc0003892f0, 0xc0003b8300, 0xc08624130b001e15, 0x12f8827ac, 0x2b3fbe0, 0xc00000fcd8, 0x0, 0x1, 0x203000)
06:18:47 observatorium_api: /usr/local/go/src/net/http/client.go:175 +0xff
06:18:47 observatorium_api: net/http.(*Client).do(0xc0003892f0, 0xc0003b8300, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/net/http/client.go:717 +0x45f
06:18:47 observatorium_api: net/http.(*Client).Do(...)
06:18:47 observatorium_api: /usr/local/go/src/net/http/client.go:585
06:18:47 observatorium_api: github.com/coreos/go-oidc.doRequest(0x1f1c5a8, 0xc000389350, 0xc0003b8200, 0x3, 0xc00003f590, 0x4c)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:63 +0x12d
06:18:47 observatorium_api: github.com/coreos/go-oidc.NewProvider(0x1f1c5a8, 0xc000389350, 0xc000092540, 0x2b, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:119 +0x149
06:18:47 observatorium_api: github.com/observatorium/api/authentication.newOIDCProvider(0x1f1c5a8, 0xc000389320, 0xc000443af4, 0x9, 0xc0003892f0, 0xc000092540, 0x2b, 0xc00000fc40, 0x1edf920, 0xc0000c0690, ...)
06:18:47 observatorium_api: /home/circleci/project/authentication/oidc.go:180 +0x20f
06:18:47 observatorium_api: github.com/observatorium/api/authentication.newOIDCAuthenticator(0xc00050dd10, 0xc000443af4, 0x9, 0xc00000fc40, 0x1edf920, 0xc0000c0690, 0x0, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /home/circleci/project/authentication/oidc.go:135 +0x2e9
06:18:47 observatorium_api: github.com/observatorium/api/authentication.(*ProviderManager).InitializeProvider.func1(0xc000443af0, 0x4, 0xc00035d130, 0xc000443af4, 0x9, 0xc0000834a0, 0xc00050dd10, 0xc00000fc40, 0x1edf920, 0xc0000c0690)
06:18:47 observatorium_api: /home/circleci/project/authentication/authentication.go:84 +0x330
06:18:47 observatorium_api: created by github.com/observatorium/api/authentication.(*ProviderManager).InitializeProvider
06:18:47 observatorium_api: /home/circleci/project/authentication/authentication.go:76 +0xd3
06:18:47 observatorium_api: goroutine 5 [runnable]:
06:18:47 observatorium_api: github.com/go-chi/chi.endpoints.Value(...)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/tree.go:121
06:18:47 observatorium_api: github.com/go-chi/chi.(*node).setEndpoint(0xc0004b1ae0, 0x3ff, 0x1edf8a0, 0xc000550400, 0x1ca0ad5, 0xe)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/tree.go:348 +0x316
06:18:47 observatorium_api: github.com/go-chi/chi.(*node).InsertRoute(0xc0004b0aa0, 0x3ff, 0x1ca0ad5, 0xe, 0x1edf8a0, 0xc000550400, 0xc00039ecf0)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/tree.go:213 +0x4bc
06:18:47 observatorium_api: github.com/go-chi/chi.(*Mux).handle(0xc000181f20, 0x3ff, 0x1ca0ad5, 0xe, 0x1ee4380, 0xc0004a85a0, 0x10)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:400 +0x9b
06:18:47 observatorium_api: github.com/go-chi/chi.(*Mux).Mount(0xc000181f20, 0x1ca0ad5, 0xe, 0x1ee4380, 0xc0004a8580)
06:18:47 observatorium_api: /home/circleci/.go_workspace/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:302 +0x1ac
06:18:47 observatorium_api: main.main.func4.1(0xc00035d130, 0xc00000fc40, 0x1edf920, 0xc0000c0690, 0xc000415068, 0xc000388630, 0x1f3d3d8, 0xc000181f20, 0xc00014f410, 0x1c9372f, ...)
06:18:47 observatorium_api: /home/circleci/project/main.go:508 +0x24e
06:18:47 observatorium_api: created by main.main.func4
06:18:47 observatorium_api: /home/circleci/project/main.go:500 +0x7d1
06:18:47 observatorium_api: goroutine 118 [runnable]:
06:18:47 observatorium_api: net/http.(*http2ClientConn).readLoop(0xc000508180)
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:8241
06:18:47 observatorium_api: created by net/http.(*http2Transport).newClientConn
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:7208 +0x6c5
06:18:47 observatorium_api: goroutine 116 [IO wait]:
06:18:47 observatorium_api: internal/poll.runtime_pollWait(0x7f64f1cb0f68, 0x72, 0xffffffffffffffff)
06:18:47 observatorium_api: /usr/local/go/src/runtime/netpoll.go:222 +0x55
06:18:47 observatorium_api: internal/poll.(*pollDesc).wait(0xc000335f18, 0x72, 0x600, 0x6b9, 0xffffffffffffffff)
06:18:47 observatorium_api: /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
06:18:47 observatorium_api: internal/poll.(*pollDesc).waitRead(...)
06:18:47 observatorium_api: /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
06:18:47 observatorium_api: internal/poll.(*FD).Read(0xc000335f00, 0xc00020ce00, 0x6b9, 0x6b9, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
06:18:47 observatorium_api: net.(*netFD).Read(0xc000335f00, 0xc00020ce00, 0x6b9, 0x6b9, 0x5f1, 0xc00020cec3, 0x5)
06:18:47 observatorium_api: /usr/local/go/src/net/fd_posix.go:55 +0x4f
06:18:47 observatorium_api: net.(*conn).Read(0xc00000fce8, 0xc00020ce00, 0x6b9, 0x6b9, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/net/net.go:183 +0x91
06:18:47 observatorium_api: crypto/tls.(*atLeastReader).Read(0xc00039ec30, 0xc00020ce00, 0x6b9, 0x6b9, 0x5f1, 0xc00023e800, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/crypto/tls/conn.go:776 +0x63
06:18:47 observatorium_api: bytes.(*Buffer).ReadFrom(0xc000364978, 0x1edf540, 0xc00039ec30, 0x40b925, 0x1a6dfa0, 0x1c16d00)
06:18:47 observatorium_api: /usr/local/go/src/bytes/buffer.go:204 +0xbe
06:18:47 observatorium_api: crypto/tls.(*Conn).readFromUntil(0xc000364700, 0x1ee29a0, 0xc00000fce8, 0x5, 0xc00000fce8, 0x4bf)
06:18:47 observatorium_api: /usr/local/go/src/crypto/tls/conn.go:798 +0xf3
06:18:47 observatorium_api: crypto/tls.(*Conn).readRecordOrCCS(0xc000364700, 0x0, 0x0, 0x1)
06:18:47 observatorium_api: /usr/local/go/src/crypto/tls/conn.go:605 +0x115
06:18:47 observatorium_api: crypto/tls.(*Conn).readRecord(...)
06:18:47 observatorium_api: /usr/local/go/src/crypto/tls/conn.go:573
06:18:47 observatorium_api: crypto/tls.(*Conn).Read(0xc000364700, 0xc00050b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/crypto/tls/conn.go:1276 +0x165
06:18:47 observatorium_api: bufio.(*Reader).Read(0xc0004fb0e0, 0xc00030e738, 0x9, 0x9, 0x6d24cb, 0xc0000a9c78, 0x406fa5)
06:18:47 observatorium_api: /usr/local/go/src/bufio/bufio.go:227 +0x222
06:18:47 observatorium_api: io.ReadAtLeast(0x1edf380, 0xc0004fb0e0, 0xc00030e738, 0x9, 0x9, 0x9, 0xc00054e320, 0xbaf368705a8200, 0xc00054e320)
06:18:47 observatorium_api: /usr/local/go/src/io/io.go:328 +0x87
06:18:47 observatorium_api: io.ReadFull(...)
06:18:47 observatorium_api: /usr/local/go/src/io/io.go:347
06:18:47 observatorium_api: net/http.http2readFrameHeader(0xc00030e738, 0x9, 0x9, 0x1edf380, 0xc0004fb0e0, 0x0, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:1477 +0x89
06:18:47 observatorium_api: net/http.(*http2Framer).ReadFrame(0xc00030e700, 0xc0005125a0, 0x0, 0x0, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:1735 +0xa5
06:18:47 observatorium_api: net/http.(*http2clientConnReadLoop).run(0xc0000a9fa8, 0x0, 0x0)
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:8322 +0xd8
06:18:47 observatorium_api: net/http.(*http2ClientConn).readLoop(0xc000508000)
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:8244 +0x6f
06:18:47 observatorium_api: created by net/http.(*http2Transport).newClientConn
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:7208 +0x6c5
06:18:47 observatorium_api: goroutine 119 [runnable]:
06:18:47 observatorium_api: net/http.(*http2clientStream).awaitRequestCancel(0xc00047d080, 0xc0003b8000)
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:6845
06:18:47 observatorium_api: created by net/http.(*http2clientConnReadLoop).handleResponse
06:18:47 observatorium_api: /usr/local/go/src/net/http/h2_bundle.go:8557 +0x728
```

</details>

I think the most interesting are goroutines 1 and 5, which indicate to me that Chi is trying to write and read to the `endpoints` map concurrently. In particular, invoking `Routes` seem to be causing to read `endpoints` map [here](https://github.com/go-chi/chi/blob/c97bc988430d623a14f50b7019fb40529036a35a/tree.go#L598) while at the same the during `Mount` method execution, the `endpoints.Value` can write to the map [here](https://github.com/go-chi/chi/blob/c97bc988430d623a14f50b7019fb40529036a35a/tree.go#L120).

I was wondering whether this is a known issue / valid bug? Thanks!

**Comment by pkieltyka** [comment]
Routes() is concurrent-safe so long as you read from it after the router has been created.

**Comment by matej-g** [comment]
The tests I mentioned are E2E tests where we're running the actual service and we hit a panic on a test run. 

We weren't aware that this is a potential issue, since we have a piece of logic that, at the beginning, starts mounting paths, based on some conditions. So sometimes the paths might get mounted e.g. 1-2 second after the mux is created and the service is started. At that point we're already serving the API discovery endpoint which is calling `Routes()` to obtain list of routes.
