### ISSUE TITLE
chi v5 panic

### ISSUE THREAD

**Issue by iliesh** [go-chi/chi#744]
So far I've used "github.com/go-chi/chi v1.5.4" in one of my projects and it was working perfectly until I decided to use the opentelemetry library which seems to be working with chi v5 only. I upgraded the library to v5 "github.com/go-chi/chi/v5 v5.0.7" and on each HTTP request the application is crashing, see below the stacktrace:

```
2022/08/22 16:37:30 http: panic serving 127.0.0.1:40746: runtime error: invalid memory address or nil pointer dereference
goroutine 69 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go/src/net/http/server.go:1850 +0x110
panic({0xe0c160, 0x1483b90})
        /usr/lib/go/src/runtime/panic.go:890 +0x262
net/http.(*timeoutHandler).ServeHTTP(0xc0003efc00, {0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /usr/lib/go/src/net/http/server.go:3412 +0xcad
net/http.HandlerFunc.ServeHTTP(0xc000248438, {0x1022310, 0xc0003e81c0}, 0xc000100000?)
        /usr/lib/go/src/net/http/server.go:2109 +0x4e
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000384780, {0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0x738
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x50e
net/http.HandlerFunc.ServeHTTP(0xc0001444a0, {0x1022310, 0xc0003e81c0}, 0xc0005d00fd?)
        /usr/lib/go/src/net/http/server.go:2109 +0x4e
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000384660, {0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x4a7
net/http.HandlerFunc.ServeHTTP(0xc000458390, {0x1022310, 0xc0003e81c0}, 0x0?)
        /usr/lib/go/src/net/http/server.go:2109 +0x4e
github.com/didip/tollbooth_chi.(*limiterWrapper).ServeHTTP(0xc000248468, {0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/didip/tollbooth_chi@v0.0.0-20220719025231-d662a7f6928f/tollbooth_chi.go:43 +0x3bf
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000384660, {0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0x738
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x50e
net/http.HandlerFunc.ServeHTTP(0xc0001444e0, {0x1022310, 0xc0003e81c0}, 0xc0003526c0?)
        /usr/lib/go/src/net/http/server.go:2109 +0x4e
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000384600, {0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x4a7
net/http.HandlerFunc.ServeHTTP(0xc0004583d0, {0x1022310, 0xc0003e81c0}, 0xc000100000?)
        /usr/lib/go/src/net/http/server.go:2109 +0x4e
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000384600, {0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0x738
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x50e
net/http.HandlerFunc.ServeHTTP(0xc000144500, {0x1022310, 0xc0003e81c0}, 0xc00013a1e4?)
        /usr/lib/go/src/net/http/server.go:2109 +0x4e
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000384300, {0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x4a7
net/http.HandlerFunc.ServeHTTP(0xc000458280, {0x1022310, 0xc0003e81c0}, 0xc00031c200?)
        /usr/lib/go/src/net/http/server.go:2109 +0x4e
github.com/go-chi/cors.(*Cors).Handler.func1({0x1022310, 0xc0003e81c0}, 0xc00031c200)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x32b
net/http.HandlerFunc.ServeHTTP(0xc000144420, {0x1022310, 0xc0003e81c0}, 0x1483830?)
        /usr/lib/go/src/net/http/server.go:2109 +0x4e
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000384300, {0x1022310, 0xc0003e81c0}, 0xc00031c100)
        /home/admin_dev/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:88 +0x6bc
net/http.serverHandler.ServeHTTP({0xc00058aff0?}, {0x1022310, 0xc0003e81c0}, 0xc00031c100)
        /usr/lib/go/src/net/http/server.go:2947 +0x642
net/http.(*conn).serve(0xc00058e280, {0x1022c38, 0xc00058ade0})
        /usr/lib/go/src/net/http/server.go:1991 +0xbe5
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:3102 +0x838
```
downgrading back to v1 it's working perfectly. Any thoughts on why it wouldn't work with v5?

**Comment by pkieltyka** [comment]
The error looks related to one of the middle area. Tollbooth_chi ?

**Comment by iliesh** [comment]
You're right, it was because of one middleware, wasn't Tollbooth but Prometheus metrics. I disabled it and now all HTTP requests seem to be working correctly.

Thanks.
